language: generic
sudo: required
dist: trusty

jobs:
  include:
    - stage: tests
      os: osx
      osx_image: xcode9.4
      env: SWIFT_VERSION=4.0

    - stage: tests
      os: osx
      osx_image: xcode9.4
      env: SWIFT_VERSION=4.1

    - stage: tests
      os: osx
      osx_image: xcode10.1
      env: SWIFT_VERSION=4.1

    - stage: tests
      os: osx
      osx_image: xcode10.1
      env: SWIFT_VERSION=4.2

    - stage: tests
      os: linux
      env: SWIFT_VERSION=4.0

    - stage: tests
      os: linux
      env: SWIFT_VERSION=4.1

    - stage: tests
      os: linux
      env: SWIFT_VERSION=4.2

    - stage: code coverage
      os: osx
      osx_image: xcode10.1
      script: make coverage
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: lint
      os: osx
      install: ./Tests/Scripts/install_dependencies.sh swiftlint
      before_script: skip
      script: ${PWD}/swiftlint/swiftlint --strict


install:
  - INSTALLER=Tests/Scripts/install_dependencies.sh
  - export LIBMONGOC_VERSION=r1.13
  - export MONGODB_VERSION=3.6.5
  - ./${INSTALLER} libmongoc
  - ./${INSTALLER} mongodb
  - if [[ "$TRAVIS_STAGE_NAME" != "Code coverage" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi

before_script:
  - MONGODIR=${PWD}/mongodb-${MONGODB_VERSION}
  - mkdir ${MONGODIR}/data
  - ${MONGODIR}/bin/mongod --dbpath ${MONGODIR}/data --logpath ${MONGODIR}/mongodb.log --fork

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test-pretty; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test; fi