language: generic
sudo: required
dist: trusty

matrix:
  include:
    - name: Lint
      os: osx
      env: TASK=LINT
    - name: Code coverage
      os: osx
      osx_image: xcode10.1
      env: MONGODB_VERSION=3.6.5 LIBMONGOC_VERSION=r.1.13 TASK=COV
    - os: osx
      osx_image: xcode9.4 
      env: MONGODB_VERSION=3.6.5 LIBMONGOC_VERSION=r.1.13 SWIFT_VERSION=4.0 TASK=TEST
    - os: osx
      osx_image: xcode9.4
      env: MONGODB_VERSION=3.6.5 LIBMONGOC_VERSION=r.1.13 SWIFT_VERSION=4.1 TASK=TEST
    - os: osx
      osx_image: xcode10.1
      env: MONGODB_VERSION=3.6.5 LIBMONGOC_VERSION=r.1.13 SWIFT_VERSION=4.1 TASK=TEST
    - os: osx
      osx_image: xcode10.1
      env: MONGODB_VERSION=3.6.5 LIBMONGOC_VERSION=r.1.13 SWIFT_VERSION=4.2 TASK=TEST
    - os: linux
      env: MONGODB_VERSION=3.6.5 LIBMONGOC_VERSION=r.1.13 SWIFT_VERSION=4.0 TASK=TEST
    - os: linux
      env: MONGODB_VERSION=3.6.5 LIBMONGOC_VERSION=r.1.13 SWIFT_VERSION=4.1 TASK=TEST
    - os: linux
      env: MONGODB_VERSION=3.6.5 LIBMONGOC_VERSION=r.1.13 SWIFT_VERSION=4.2 TASK=TEST

install:
  - INSTALLER=Tests/Scripts/install_dependencies.sh
  - if [[ "$TASK" == "TEST" ]]; then ./${INSTALLER} libmongoc; eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; ./${INSTALLER} mongodb; fi
  - if [[ "$TASK" == "LINT" ]]; then ./${INSTALLER} swiftlint; fi
  - if [[ "$TASK" == "COV" ]]; then ./${INSTALLER} libmongoc; ./${INSTALLER} mongodb; fi

before_script:
  - MONGODIR=${PWD}/mongodb-${MONGODB_VERSION}
  - if [[ "$TASK" != "LINT" ]]; then mkdir ${MONGODIR}/data; ${MONGODIR}/bin/mongod --dbpath ${MONGODIR}/data --logpath ${MONGODIR}/mongodb.log --fork; fi

script:
  - if [[ "$TASK" == "TEST" ]]; then make test-pretty; fi
  - if [[ "$TASK" == "LINT" ]]; then ${PWD}/swiftlint/swiftlint --strict; fi 
  - if [[ "$TASK" == "COV" ]]; then make coverage; fi

after_success:
  - if [[ "$TASK" == "COV" ]]; then  bash <(curl -s https://codecov.io/bash); fi
